package com.min01.oceanicrealms.entity.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class HammerheadSharkAnimation 
{
	public static final AnimationDefinition HAMMERHEAD_SHARK_SWIM = AnimationDefinition.Builder.withLength(1.3722F).looping()
			.addAnimation("bone", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0653F, KeyframeAnimations.degreeVec(0.0F, 1.03F, -1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1633F, KeyframeAnimations.degreeVec(0.0F, 1.93F, -1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2287F, KeyframeAnimations.degreeVec(0.0F, 2.6F, -1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.294F, KeyframeAnimations.degreeVec(0.0F, 2.95F, -0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.392F, KeyframeAnimations.degreeVec(0.0F, 2.95F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4574F, KeyframeAnimations.degreeVec(0.0F, 2.6F, 0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5227F, KeyframeAnimations.degreeVec(0.0F, 1.93F, 1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6534F, KeyframeAnimations.degreeVec(0.0F, 0.52F, 1.88F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7187F, KeyframeAnimations.degreeVec(0.0F, -0.52F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7841F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 1.88F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8821F, KeyframeAnimations.degreeVec(0.0F, -2.3F, 1.53F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9474F, KeyframeAnimations.degreeVec(0.0F, -2.82F, 1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0127F, KeyframeAnimations.degreeVec(0.0F, -3.0F, 0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1107F, KeyframeAnimations.degreeVec(0.0F, -2.82F, -0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1761F, KeyframeAnimations.degreeVec(0.0F, -2.3F, -1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3068F, KeyframeAnimations.degreeVec(0.0F, -1.03F, -1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3721F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.97F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone", new AnimationChannel(AnimationChannel.Targets.POSITION, 
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0327F, KeyframeAnimations.posVec(1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0653F, KeyframeAnimations.posVec(0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.098F, KeyframeAnimations.posVec(0.94F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1633F, KeyframeAnimations.posVec(0.87F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.196F, KeyframeAnimations.posVec(0.77F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2614F, KeyframeAnimations.posVec(0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4574F, KeyframeAnimations.posVec(-0.34F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.49F, KeyframeAnimations.posVec(-0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5554F, KeyframeAnimations.posVec(-0.77F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6207F, KeyframeAnimations.posVec(-0.87F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6534F, KeyframeAnimations.posVec(-0.94F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6861F, KeyframeAnimations.posVec(-0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7187F, KeyframeAnimations.posVec(-1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7514F, KeyframeAnimations.posVec(-0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7841F, KeyframeAnimations.posVec(-0.94F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8494F, KeyframeAnimations.posVec(-0.87F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8821F, KeyframeAnimations.posVec(-0.77F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9474F, KeyframeAnimations.posVec(-0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1434F, KeyframeAnimations.posVec(0.34F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1761F, KeyframeAnimations.posVec(0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2414F, KeyframeAnimations.posVec(0.77F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3068F, KeyframeAnimations.posVec(0.87F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3394F, KeyframeAnimations.posVec(0.94F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3721F, KeyframeAnimations.posVec(0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone2", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -5.64F, -0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0327F, KeyframeAnimations.degreeVec(0.0F, -5.2F, -0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0653F, KeyframeAnimations.degreeVec(0.0F, -4.6F, -1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.098F, KeyframeAnimations.degreeVec(0.0F, -3.86F, -1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.196F, KeyframeAnimations.degreeVec(0.0F, -2.05F, -1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2614F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.3267F, KeyframeAnimations.degreeVec(0.0F, 2.05F, -1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4247F, KeyframeAnimations.degreeVec(0.0F, 3.86F, -1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4574F, KeyframeAnimations.degreeVec(0.0F, 4.6F, -1.53F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.49F, KeyframeAnimations.degreeVec(0.0F, 5.2F, -1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5227F, KeyframeAnimations.degreeVec(0.0F, 5.64F, -1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5554F, KeyframeAnimations.degreeVec(0.0F, 5.91F, -0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6207F, KeyframeAnimations.degreeVec(0.0F, 6.0F, -0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6534F, KeyframeAnimations.degreeVec(0.0F, 5.91F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6861F, KeyframeAnimations.degreeVec(0.0F, 5.64F, 0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7187F, KeyframeAnimations.degreeVec(0.0F, 5.2F, 0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7514F, KeyframeAnimations.degreeVec(0.0F, 4.6F, 1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7841F, KeyframeAnimations.degreeVec(0.0F, 3.86F, 1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8821F, KeyframeAnimations.degreeVec(0.0F, 2.05F, 1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9474F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0127F, KeyframeAnimations.degreeVec(0.0F, -2.05F, 1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1107F, KeyframeAnimations.degreeVec(0.0F, -3.86F, 1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1434F, KeyframeAnimations.degreeVec(0.0F, -4.6F, 1.53F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1761F, KeyframeAnimations.degreeVec(0.0F, -5.2F, 1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2088F, KeyframeAnimations.degreeVec(0.0F, -5.64F, 1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2414F, KeyframeAnimations.degreeVec(0.0F, -5.91F, 0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3068F, KeyframeAnimations.degreeVec(0.0F, -6.0F, 0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3394F, KeyframeAnimations.degreeVec(0.0F, -5.91F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3721F, KeyframeAnimations.degreeVec(0.0F, -5.64F, -0.35F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone3", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -9.85F, 1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0327F, KeyframeAnimations.degreeVec(0.0F, -10.0F, 0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0653F, KeyframeAnimations.degreeVec(0.0F, -9.85F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.098F, KeyframeAnimations.degreeVec(0.0F, -9.4F, -0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1633F, KeyframeAnimations.degreeVec(0.0F, -8.66F, -1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.196F, KeyframeAnimations.degreeVec(0.0F, -7.66F, -2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2287F, KeyframeAnimations.degreeVec(0.0F, -6.43F, -2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2614F, KeyframeAnimations.degreeVec(0.0F, -5.0F, -3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.3267F, KeyframeAnimations.degreeVec(0.0F, -1.74F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.392F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4247F, KeyframeAnimations.degreeVec(0.0F, 1.74F, -4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4574F, KeyframeAnimations.degreeVec(0.0F, 3.42F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.49F, KeyframeAnimations.degreeVec(0.0F, 5.0F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5227F, KeyframeAnimations.degreeVec(0.0F, 6.43F, -3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5554F, KeyframeAnimations.degreeVec(0.0F, 7.66F, -3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6207F, KeyframeAnimations.degreeVec(0.0F, 8.66F, -2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6534F, KeyframeAnimations.degreeVec(0.0F, 9.4F, -2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6861F, KeyframeAnimations.degreeVec(0.0F, 9.85F, -1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7187F, KeyframeAnimations.degreeVec(0.0F, 10.0F, -0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7514F, KeyframeAnimations.degreeVec(0.0F, 9.85F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7841F, KeyframeAnimations.degreeVec(0.0F, 9.4F, 0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8494F, KeyframeAnimations.degreeVec(0.0F, 8.66F, 1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8821F, KeyframeAnimations.degreeVec(0.0F, 7.66F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9147F, KeyframeAnimations.degreeVec(0.0F, 6.43F, 2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9474F, KeyframeAnimations.degreeVec(0.0F, 5.0F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0127F, KeyframeAnimations.degreeVec(0.0F, 1.74F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0781F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1107F, KeyframeAnimations.degreeVec(0.0F, -1.74F, 4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1434F, KeyframeAnimations.degreeVec(0.0F, -3.42F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1761F, KeyframeAnimations.degreeVec(0.0F, -5.0F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2088F, KeyframeAnimations.degreeVec(0.0F, -6.43F, 3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2414F, KeyframeAnimations.degreeVec(0.0F, -7.66F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3068F, KeyframeAnimations.degreeVec(0.0F, -8.66F, 2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3394F, KeyframeAnimations.degreeVec(0.0F, -9.4F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3721F, KeyframeAnimations.degreeVec(0.0F, -9.85F, 1.37F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone11", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 6.84F, 4.7F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0327F, KeyframeAnimations.degreeVec(0.0F, 3.47F, 4.33F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0653F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.83F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1633F, KeyframeAnimations.degreeVec(0.0F, -6.84F, 2.5F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.196F, KeyframeAnimations.degreeVec(0.0F, -10.0F, 1.71F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2287F, KeyframeAnimations.degreeVec(0.0F, -12.86F, 0.87F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2614F, KeyframeAnimations.degreeVec(0.0F, -15.32F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.294F, KeyframeAnimations.degreeVec(0.0F, -17.32F, -0.87F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.3267F, KeyframeAnimations.degreeVec(0.0F, -18.79F, -1.71F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.392F, KeyframeAnimations.degreeVec(0.0F, -19.7F, -2.5F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4247F, KeyframeAnimations.degreeVec(0.0F, -20.0F, -3.21F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4574F, KeyframeAnimations.degreeVec(0.0F, -19.7F, -3.83F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.49F, KeyframeAnimations.degreeVec(0.0F, -18.79F, -4.33F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5227F, KeyframeAnimations.degreeVec(0.0F, -17.32F, -4.7F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5554F, KeyframeAnimations.degreeVec(0.0F, -15.32F, -4.92F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6207F, KeyframeAnimations.degreeVec(0.0F, -12.86F, -5.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6534F, KeyframeAnimations.degreeVec(0.0F, -10.0F, -4.92F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6861F, KeyframeAnimations.degreeVec(0.0F, -6.84F, -4.7F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7187F, KeyframeAnimations.degreeVec(0.0F, -3.47F, -4.33F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7514F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.83F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7841F, KeyframeAnimations.degreeVec(0.0F, 3.47F, -3.21F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8494F, KeyframeAnimations.degreeVec(0.0F, 6.84F, -2.5F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8821F, KeyframeAnimations.degreeVec(0.0F, 10.0F, -1.71F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9147F, KeyframeAnimations.degreeVec(0.0F, 12.86F, -0.87F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9474F, KeyframeAnimations.degreeVec(0.0F, 15.32F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9801F, KeyframeAnimations.degreeVec(0.0F, 17.32F, 0.87F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0127F, KeyframeAnimations.degreeVec(0.0F, 18.79F, 1.71F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0781F, KeyframeAnimations.degreeVec(0.0F, 19.7F, 2.5F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1107F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 3.21F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1434F, KeyframeAnimations.degreeVec(0.0F, 19.7F, 3.83F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1761F, KeyframeAnimations.degreeVec(0.0F, 18.79F, 4.33F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2088F, KeyframeAnimations.degreeVec(0.0F, 17.32F, 4.7F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2414F, KeyframeAnimations.degreeVec(0.0F, 15.32F, 4.92F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3068F, KeyframeAnimations.degreeVec(0.0F, 12.86F, 5.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3394F, KeyframeAnimations.degreeVec(0.0F, 10.0F, 4.92F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3721F, KeyframeAnimations.degreeVec(0.0F, 6.84F, 4.7F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone9", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0653F, KeyframeAnimations.degreeVec(0.0F, -2.3F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1633F, KeyframeAnimations.degreeVec(0.0F, -2.82F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2287F, KeyframeAnimations.degreeVec(0.0F, -3.0F, 0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.294F, KeyframeAnimations.degreeVec(0.0F, -2.82F, -0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.392F, KeyframeAnimations.degreeVec(0.0F, -2.3F, -2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4574F, KeyframeAnimations.degreeVec(0.0F, -1.5F, -3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5227F, KeyframeAnimations.degreeVec(0.0F, -0.52F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5554F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6207F, KeyframeAnimations.degreeVec(0.0F, 0.52F, -4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6534F, KeyframeAnimations.degreeVec(0.0F, 1.03F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6861F, KeyframeAnimations.degreeVec(0.0F, 1.5F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7187F, KeyframeAnimations.degreeVec(0.0F, 1.93F, -3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7841F, KeyframeAnimations.degreeVec(0.0F, 2.6F, -2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8821F, KeyframeAnimations.degreeVec(0.0F, 2.95F, -1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9474F, KeyframeAnimations.degreeVec(0.0F, 2.95F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0127F, KeyframeAnimations.degreeVec(0.0F, 2.6F, 1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1107F, KeyframeAnimations.degreeVec(0.0F, 1.93F, 2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1761F, KeyframeAnimations.degreeVec(0.0F, 1.03F, 3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2088F, KeyframeAnimations.degreeVec(0.0F, 0.52F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2414F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3068F, KeyframeAnimations.degreeVec(0.0F, -0.52F, 4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3394F, KeyframeAnimations.degreeVec(0.0F, -1.03F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3721F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 3.76F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone10", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0653F, KeyframeAnimations.degreeVec(0.0F, -2.3F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1633F, KeyframeAnimations.degreeVec(0.0F, -2.82F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2287F, KeyframeAnimations.degreeVec(0.0F, -3.0F, 0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.294F, KeyframeAnimations.degreeVec(0.0F, -2.82F, -0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.392F, KeyframeAnimations.degreeVec(0.0F, -2.3F, -2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4574F, KeyframeAnimations.degreeVec(0.0F, -1.5F, -3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5227F, KeyframeAnimations.degreeVec(0.0F, -0.52F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5554F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6207F, KeyframeAnimations.degreeVec(0.0F, 0.52F, -4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6534F, KeyframeAnimations.degreeVec(0.0F, 1.03F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6861F, KeyframeAnimations.degreeVec(0.0F, 1.5F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7187F, KeyframeAnimations.degreeVec(0.0F, 1.93F, -3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7841F, KeyframeAnimations.degreeVec(0.0F, 2.6F, -2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8821F, KeyframeAnimations.degreeVec(0.0F, 2.95F, -1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9474F, KeyframeAnimations.degreeVec(0.0F, 2.95F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0127F, KeyframeAnimations.degreeVec(0.0F, 2.6F, 1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1107F, KeyframeAnimations.degreeVec(0.0F, 1.93F, 2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1761F, KeyframeAnimations.degreeVec(0.0F, 1.03F, 3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2088F, KeyframeAnimations.degreeVec(0.0F, 0.52F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2414F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3068F, KeyframeAnimations.degreeVec(0.0F, -0.52F, 4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3394F, KeyframeAnimations.degreeVec(0.0F, -1.03F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3721F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 3.76F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone4", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 2.95F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.0653F, KeyframeAnimations.degreeVec(0.0F, 2.6F, 0.68F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.1633F, KeyframeAnimations.degreeVec(0.0F, 1.93F, 1.29F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2614F, KeyframeAnimations.degreeVec(0.0F, 0.52F, 1.88F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.3267F, KeyframeAnimations.degreeVec(0.0F, -0.52F, 2.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4247F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 1.88F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.49F, KeyframeAnimations.degreeVec(0.0F, -2.3F, 1.53F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5554F, KeyframeAnimations.degreeVec(0.0F, -2.82F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6534F, KeyframeAnimations.degreeVec(0.0F, -3.0F, 0.35F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7187F, KeyframeAnimations.degreeVec(0.0F, -2.82F, -0.35F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7841F, KeyframeAnimations.degreeVec(0.0F, -2.3F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9147F, KeyframeAnimations.degreeVec(0.0F, -1.03F, -1.73F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9801F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.97F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0781F, KeyframeAnimations.degreeVec(0.0F, 1.03F, -1.97F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.1434F, KeyframeAnimations.degreeVec(0.0F, 1.93F, -1.73F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2088F, KeyframeAnimations.degreeVec(0.0F, 2.6F, -1.29F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3068F, KeyframeAnimations.degreeVec(0.0F, 2.95F, -0.68F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3721F, KeyframeAnimations.degreeVec(0.0F, 2.95F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("bone6", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.34F, 0.87F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1633F, KeyframeAnimations.degreeVec(0.64F, -0.34F, 0.98F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.294F, KeyframeAnimations.degreeVec(0.98F, -0.87F, 0.64F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4574F, KeyframeAnimations.degreeVec(0.87F, -0.98F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6207F, KeyframeAnimations.degreeVec(0.34F, -0.64F, -0.64F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7514F, KeyframeAnimations.degreeVec(-0.34F, 0.0F, -0.98F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9147F, KeyframeAnimations.degreeVec(-0.87F, 0.64F, -0.87F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0781F, KeyframeAnimations.degreeVec(-0.98F, 0.98F, -0.34F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2088F, KeyframeAnimations.degreeVec(-0.64F, 0.87F, 0.34F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3721F, KeyframeAnimations.degreeVec(0.0F, 0.34F, 0.87F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone7", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -2.95F, 1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0653F, KeyframeAnimations.degreeVec(0.0F, -2.95F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1633F, KeyframeAnimations.degreeVec(0.0F, -2.6F, -1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2287F, KeyframeAnimations.degreeVec(0.0F, -1.93F, -2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.294F, KeyframeAnimations.degreeVec(0.0F, -1.03F, -3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.3267F, KeyframeAnimations.degreeVec(0.0F, -0.52F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.392F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4247F, KeyframeAnimations.degreeVec(0.0F, 0.52F, -4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4574F, KeyframeAnimations.degreeVec(0.0F, 1.03F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.49F, KeyframeAnimations.degreeVec(0.0F, 1.5F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5554F, KeyframeAnimations.degreeVec(0.0F, 2.3F, -3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6534F, KeyframeAnimations.degreeVec(0.0F, 2.82F, -2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7187F, KeyframeAnimations.degreeVec(0.0F, 3.0F, -0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7841F, KeyframeAnimations.degreeVec(0.0F, 2.82F, 0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8821F, KeyframeAnimations.degreeVec(0.0F, 2.3F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9474F, KeyframeAnimations.degreeVec(0.0F, 1.5F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0127F, KeyframeAnimations.degreeVec(0.0F, 0.52F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0781F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1107F, KeyframeAnimations.degreeVec(0.0F, -0.52F, 4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1434F, KeyframeAnimations.degreeVec(0.0F, -1.03F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1761F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2414F, KeyframeAnimations.degreeVec(0.0F, -2.3F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3394F, KeyframeAnimations.degreeVec(0.0F, -2.82F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3721F, KeyframeAnimations.degreeVec(0.0F, -2.95F, 1.37F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone8", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -2.95F, 1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0653F, KeyframeAnimations.degreeVec(0.0F, -2.95F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1633F, KeyframeAnimations.degreeVec(0.0F, -2.6F, -1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2287F, KeyframeAnimations.degreeVec(0.0F, -1.93F, -2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.294F, KeyframeAnimations.degreeVec(0.0F, -1.03F, -3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.3267F, KeyframeAnimations.degreeVec(0.0F, -0.52F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.392F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4247F, KeyframeAnimations.degreeVec(0.0F, 0.52F, -4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4574F, KeyframeAnimations.degreeVec(0.0F, 1.03F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.49F, KeyframeAnimations.degreeVec(0.0F, 1.5F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5554F, KeyframeAnimations.degreeVec(0.0F, 2.3F, -3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6534F, KeyframeAnimations.degreeVec(0.0F, 2.82F, -2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7187F, KeyframeAnimations.degreeVec(0.0F, 3.0F, -0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7841F, KeyframeAnimations.degreeVec(0.0F, 2.82F, 0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8821F, KeyframeAnimations.degreeVec(0.0F, 2.3F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9474F, KeyframeAnimations.degreeVec(0.0F, 1.5F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0127F, KeyframeAnimations.degreeVec(0.0F, 0.52F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0781F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1107F, KeyframeAnimations.degreeVec(0.0F, -0.52F, 4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1434F, KeyframeAnimations.degreeVec(0.0F, -1.03F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1761F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2414F, KeyframeAnimations.degreeVec(0.0F, -2.3F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3394F, KeyframeAnimations.degreeVec(0.0F, -2.82F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3721F, KeyframeAnimations.degreeVec(0.0F, -2.95F, 1.37F), AnimationChannel.Interpolations.LINEAR)
			))
			.build();

		public static final AnimationDefinition HAMMERHEAD_SHARK_ATTACK = AnimationDefinition.Builder.withLength(1.0F).looping()
			.addAnimation("bone4", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4583F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.625F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("bone4", new AnimationChannel(AnimationChannel.Targets.POSITION, 
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5417F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083F, KeyframeAnimations.posVec(0.0F, 0.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7917F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("bone5", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.1667F, KeyframeAnimations.degreeVec(-20.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167F, KeyframeAnimations.degreeVec(-20.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.625F, KeyframeAnimations.degreeVec(-45.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7917F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("bone5", new AnimationChannel(AnimationChannel.Targets.SCALE, 
				new Keyframe(0.5F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.625F, KeyframeAnimations.scaleVec(1.15F, 1.15F, 1.15F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.2F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7917F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.2F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("bone6", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2083F, KeyframeAnimations.degreeVec(20.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4583F, KeyframeAnimations.degreeVec(20.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5417F, KeyframeAnimations.degreeVec(60.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6667F, KeyframeAnimations.degreeVec(47.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8333F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("bone6", new AnimationChannel(AnimationChannel.Targets.SCALE, 
				new Keyframe(0.5417F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6667F, KeyframeAnimations.scaleVec(1.15F, 1.15F, 1.15F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.2F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8333F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.2F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.build();

		public static final AnimationDefinition HAMMERHEAD_SHARK_EATING = AnimationDefinition.Builder.withLength(1.0F).looping()
			.addAnimation("bone5", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.25F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("bone6", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.25F, KeyframeAnimations.degreeVec(12.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75F, KeyframeAnimations.degreeVec(12.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.build();
}
