package com.min01.oceanicrealms.entity.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class LionfishAnimation
{
	public static final AnimationDefinition LIONFISH_SWIM = AnimationDefinition.Builder.withLength(2.5F).looping()
			.addAnimation("bone2", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1389F, KeyframeAnimations.degreeVec(0.0F, 1.03F, -1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2778F, KeyframeAnimations.degreeVec(0.0F, 1.93F, -1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4167F, KeyframeAnimations.degreeVec(0.0F, 2.6F, -1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5556F, KeyframeAnimations.degreeVec(0.0F, 2.95F, -0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6944F, KeyframeAnimations.degreeVec(0.0F, 2.95F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8333F, KeyframeAnimations.degreeVec(0.0F, 2.6F, 0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9722F, KeyframeAnimations.degreeVec(0.0F, 1.93F, 1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1806F, KeyframeAnimations.degreeVec(0.0F, 0.52F, 1.88F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3194F, KeyframeAnimations.degreeVec(0.0F, -0.52F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.4583F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 1.88F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.5972F, KeyframeAnimations.degreeVec(0.0F, -2.3F, 1.53F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.7361F, KeyframeAnimations.degreeVec(0.0F, -2.82F, 1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.875F, KeyframeAnimations.degreeVec(0.0F, -3.0F, 0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.0139F, KeyframeAnimations.degreeVec(0.0F, -2.82F, -0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1528F, KeyframeAnimations.degreeVec(0.0F, -2.3F, -1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.3611F, KeyframeAnimations.degreeVec(0.0F, -1.03F, -1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.97F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone2", new AnimationChannel(AnimationChannel.Targets.POSITION, 
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0694F, KeyframeAnimations.posVec(1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1389F, KeyframeAnimations.posVec(0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2083F, KeyframeAnimations.posVec(0.94F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2778F, KeyframeAnimations.posVec(0.87F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.3472F, KeyframeAnimations.posVec(0.77F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4861F, KeyframeAnimations.posVec(0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8333F, KeyframeAnimations.posVec(-0.34F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9028F, KeyframeAnimations.posVec(-0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0417F, KeyframeAnimations.posVec(-0.77F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1111F, KeyframeAnimations.posVec(-0.87F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1806F, KeyframeAnimations.posVec(-0.94F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.25F, KeyframeAnimations.posVec(-0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3194F, KeyframeAnimations.posVec(-1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3889F, KeyframeAnimations.posVec(-0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.4583F, KeyframeAnimations.posVec(-0.94F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.5278F, KeyframeAnimations.posVec(-0.87F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.5972F, KeyframeAnimations.posVec(-0.77F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.7361F, KeyframeAnimations.posVec(-0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.0833F, KeyframeAnimations.posVec(0.34F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1528F, KeyframeAnimations.posVec(0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.2917F, KeyframeAnimations.posVec(0.77F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.3611F, KeyframeAnimations.posVec(0.87F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4306F, KeyframeAnimations.posVec(0.94F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.5F, KeyframeAnimations.posVec(0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -9.85F, 1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0694F, KeyframeAnimations.degreeVec(0.0F, -10.0F, 0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1389F, KeyframeAnimations.degreeVec(0.0F, -9.85F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2083F, KeyframeAnimations.degreeVec(0.0F, -9.4F, -0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2778F, KeyframeAnimations.degreeVec(0.0F, -8.66F, -1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.3472F, KeyframeAnimations.degreeVec(0.0F, -7.66F, -2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4167F, KeyframeAnimations.degreeVec(0.0F, -6.43F, -2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4861F, KeyframeAnimations.degreeVec(0.0F, -5.0F, -3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.625F, KeyframeAnimations.degreeVec(0.0F, -1.74F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6944F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7639F, KeyframeAnimations.degreeVec(0.0F, 1.74F, -4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8333F, KeyframeAnimations.degreeVec(0.0F, 3.42F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9028F, KeyframeAnimations.degreeVec(0.0F, 5.0F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9722F, KeyframeAnimations.degreeVec(0.0F, 6.43F, -3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0417F, KeyframeAnimations.degreeVec(0.0F, 7.66F, -3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1111F, KeyframeAnimations.degreeVec(0.0F, 8.66F, -2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1806F, KeyframeAnimations.degreeVec(0.0F, 9.4F, -2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.25F, KeyframeAnimations.degreeVec(0.0F, 9.85F, -1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3194F, KeyframeAnimations.degreeVec(0.0F, 10.0F, -0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3889F, KeyframeAnimations.degreeVec(0.0F, 9.85F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.4583F, KeyframeAnimations.degreeVec(0.0F, 9.4F, 0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.5278F, KeyframeAnimations.degreeVec(0.0F, 8.66F, 1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.5972F, KeyframeAnimations.degreeVec(0.0F, 7.66F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.6667F, KeyframeAnimations.degreeVec(0.0F, 6.43F, 2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.7361F, KeyframeAnimations.degreeVec(0.0F, 5.0F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.875F, KeyframeAnimations.degreeVec(0.0F, 1.74F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.9444F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.0139F, KeyframeAnimations.degreeVec(0.0F, -1.74F, 4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.0833F, KeyframeAnimations.degreeVec(0.0F, -3.42F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1528F, KeyframeAnimations.degreeVec(0.0F, -5.0F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.2222F, KeyframeAnimations.degreeVec(0.0F, -6.43F, 3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.2917F, KeyframeAnimations.degreeVec(0.0F, -7.66F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.3611F, KeyframeAnimations.degreeVec(0.0F, -8.66F, 2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4306F, KeyframeAnimations.degreeVec(0.0F, -9.4F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.0F, -9.85F, 1.37F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone3", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 6.84F, 4.7F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0694F, KeyframeAnimations.degreeVec(0.0F, 3.47F, 4.33F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1389F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.83F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2778F, KeyframeAnimations.degreeVec(0.0F, -6.84F, 2.5F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.3472F, KeyframeAnimations.degreeVec(0.0F, -10.0F, 1.71F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4167F, KeyframeAnimations.degreeVec(0.0F, -12.86F, 0.87F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4861F, KeyframeAnimations.degreeVec(0.0F, -15.32F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5556F, KeyframeAnimations.degreeVec(0.0F, -17.32F, -0.87F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.625F, KeyframeAnimations.degreeVec(0.0F, -18.79F, -1.71F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6944F, KeyframeAnimations.degreeVec(0.0F, -19.7F, -2.5F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7639F, KeyframeAnimations.degreeVec(0.0F, -20.0F, -3.21F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8333F, KeyframeAnimations.degreeVec(0.0F, -19.7F, -3.83F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9028F, KeyframeAnimations.degreeVec(0.0F, -18.79F, -4.33F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9722F, KeyframeAnimations.degreeVec(0.0F, -17.32F, -4.7F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0417F, KeyframeAnimations.degreeVec(0.0F, -15.32F, -4.92F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1111F, KeyframeAnimations.degreeVec(0.0F, -12.86F, -5.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1806F, KeyframeAnimations.degreeVec(0.0F, -10.0F, -4.92F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.25F, KeyframeAnimations.degreeVec(0.0F, -6.84F, -4.7F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3194F, KeyframeAnimations.degreeVec(0.0F, -3.47F, -4.33F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3889F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.83F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.4583F, KeyframeAnimations.degreeVec(0.0F, 3.47F, -3.21F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.5278F, KeyframeAnimations.degreeVec(0.0F, 6.84F, -2.5F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.5972F, KeyframeAnimations.degreeVec(0.0F, 10.0F, -1.71F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.6667F, KeyframeAnimations.degreeVec(0.0F, 12.86F, -0.87F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.7361F, KeyframeAnimations.degreeVec(0.0F, 15.32F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.8056F, KeyframeAnimations.degreeVec(0.0F, 17.32F, 0.87F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.875F, KeyframeAnimations.degreeVec(0.0F, 18.79F, 1.71F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.9444F, KeyframeAnimations.degreeVec(0.0F, 19.7F, 2.5F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.0139F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 3.21F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.0833F, KeyframeAnimations.degreeVec(0.0F, 19.7F, 3.83F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1528F, KeyframeAnimations.degreeVec(0.0F, 18.79F, 4.33F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.2222F, KeyframeAnimations.degreeVec(0.0F, 17.32F, 4.7F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.2917F, KeyframeAnimations.degreeVec(0.0F, 15.32F, 4.92F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.3611F, KeyframeAnimations.degreeVec(0.0F, 12.86F, 5.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4306F, KeyframeAnimations.degreeVec(0.0F, 10.0F, 4.92F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.0F, 6.84F, 4.7F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("left", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7639F, KeyframeAnimations.degreeVec(0.5F, 5.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.6667F, KeyframeAnimations.degreeVec(-2.0F, 2.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("right", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7639F, KeyframeAnimations.degreeVec(0.5F, -5.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.6667F, KeyframeAnimations.degreeVec(-2.0F, -2.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.build();
}
