package com.min01.oceanicrealms.entity.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class WhalesharkAnimation
{
	public static final AnimationDefinition WHALESHARK_SWIM = AnimationDefinition.Builder.withLength(2.5205F).looping()
			.addAnimation("bone", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1172F, KeyframeAnimations.degreeVec(0.0F, 1.03F, -1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2931F, KeyframeAnimations.degreeVec(0.0F, 1.93F, -1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4103F, KeyframeAnimations.degreeVec(0.0F, 2.6F, -1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5862F, KeyframeAnimations.degreeVec(0.0F, 2.95F, -0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7034F, KeyframeAnimations.degreeVec(0.0F, 2.95F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8206F, KeyframeAnimations.degreeVec(0.0F, 2.6F, 0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9965F, KeyframeAnimations.degreeVec(0.0F, 1.93F, 1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1723F, KeyframeAnimations.degreeVec(0.0F, 0.52F, 1.88F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3482F, KeyframeAnimations.degreeVec(0.0F, -0.52F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.4654F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 1.88F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.6413F, KeyframeAnimations.degreeVec(0.0F, -2.3F, 1.53F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.7585F, KeyframeAnimations.degreeVec(0.0F, -2.82F, 1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.8757F, KeyframeAnimations.degreeVec(0.0F, -3.0F, 0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.0516F, KeyframeAnimations.degreeVec(0.0F, -2.82F, -0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1688F, KeyframeAnimations.degreeVec(0.0F, -2.3F, -1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4033F, KeyframeAnimations.degreeVec(0.0F, -1.03F, -1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.5205F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.97F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone", new AnimationChannel(AnimationChannel.Targets.POSITION, 
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0586F, KeyframeAnimations.posVec(1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1172F, KeyframeAnimations.posVec(0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2345F, KeyframeAnimations.posVec(0.94F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2931F, KeyframeAnimations.posVec(0.87F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.3517F, KeyframeAnimations.posVec(0.77F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4689F, KeyframeAnimations.posVec(0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8206F, KeyframeAnimations.posVec(-0.34F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9379F, KeyframeAnimations.posVec(-0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0551F, KeyframeAnimations.posVec(-0.77F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1137F, KeyframeAnimations.posVec(-0.87F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1723F, KeyframeAnimations.posVec(-0.94F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2896F, KeyframeAnimations.posVec(-0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3482F, KeyframeAnimations.posVec(-1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.4068F, KeyframeAnimations.posVec(-0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.4654F, KeyframeAnimations.posVec(-0.94F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.524F, KeyframeAnimations.posVec(-0.87F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.6413F, KeyframeAnimations.posVec(-0.77F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.7585F, KeyframeAnimations.posVec(-0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1102F, KeyframeAnimations.posVec(0.34F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1688F, KeyframeAnimations.posVec(0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.3447F, KeyframeAnimations.posVec(0.77F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4033F, KeyframeAnimations.posVec(0.87F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4619F, KeyframeAnimations.posVec(0.94F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.5205F, KeyframeAnimations.posVec(0.98F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone2", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -5.64F, -0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.0586F, KeyframeAnimations.degreeVec(0.0F, -5.2F, -0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1172F, KeyframeAnimations.degreeVec(0.0F, -4.6F, -1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2345F, KeyframeAnimations.degreeVec(0.0F, -3.86F, -1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.3517F, KeyframeAnimations.degreeVec(0.0F, -2.05F, -1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4689F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6448F, KeyframeAnimations.degreeVec(0.0F, 2.05F, -1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.762F, KeyframeAnimations.degreeVec(0.0F, 3.86F, -1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8206F, KeyframeAnimations.degreeVec(0.0F, 4.6F, -1.53F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9379F, KeyframeAnimations.degreeVec(0.0F, 5.2F, -1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9965F, KeyframeAnimations.degreeVec(0.0F, 5.64F, -1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0551F, KeyframeAnimations.degreeVec(0.0F, 5.91F, -0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1137F, KeyframeAnimations.degreeVec(0.0F, 6.0F, -0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1723F, KeyframeAnimations.degreeVec(0.0F, 5.91F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2896F, KeyframeAnimations.degreeVec(0.0F, 5.64F, 0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3482F, KeyframeAnimations.degreeVec(0.0F, 5.2F, 0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.4068F, KeyframeAnimations.degreeVec(0.0F, 4.6F, 1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.4654F, KeyframeAnimations.degreeVec(0.0F, 3.86F, 1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.6413F, KeyframeAnimations.degreeVec(0.0F, 2.05F, 1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.7585F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.8757F, KeyframeAnimations.degreeVec(0.0F, -2.05F, 1.97F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.0516F, KeyframeAnimations.degreeVec(0.0F, -3.86F, 1.73F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1102F, KeyframeAnimations.degreeVec(0.0F, -4.6F, 1.53F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1688F, KeyframeAnimations.degreeVec(0.0F, -5.2F, 1.29F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.2274F, KeyframeAnimations.degreeVec(0.0F, -5.64F, 1.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.3447F, KeyframeAnimations.degreeVec(0.0F, -5.91F, 0.68F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4033F, KeyframeAnimations.degreeVec(0.0F, -6.0F, 0.35F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4619F, KeyframeAnimations.degreeVec(0.0F, -5.91F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.5205F, KeyframeAnimations.degreeVec(0.0F, -5.64F, -0.35F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone3", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -10.0F, 0.69F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4103F, KeyframeAnimations.degreeVec(0.0F, -5.0F, -3.06F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8206F, KeyframeAnimations.degreeVec(0.0F, 5.0F, -3.76F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2896F, KeyframeAnimations.degreeVec(0.0F, 10.0F, -0.69F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.6999F, KeyframeAnimations.degreeVec(0.0F, 5.0F, 3.06F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.1102F, KeyframeAnimations.degreeVec(0.0F, -5.0F, 3.76F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5205F, KeyframeAnimations.degreeVec(0.0F, -10.0F, 0.69F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("bone4", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 3.47F, 4.33F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4103F, KeyframeAnimations.degreeVec(0.0F, -15.32F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8206F, KeyframeAnimations.degreeVec(0.0F, -18.79F, -4.33F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2896F, KeyframeAnimations.degreeVec(0.0F, -3.47F, -4.33F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.6999F, KeyframeAnimations.degreeVec(0.0F, 15.32F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.1102F, KeyframeAnimations.degreeVec(0.0F, 18.79F, 4.33F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5205F, KeyframeAnimations.degreeVec(0.0F, 3.47F, 4.33F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("bone5", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -2.95F, 1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1172F, KeyframeAnimations.degreeVec(0.0F, -2.95F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2931F, KeyframeAnimations.degreeVec(0.0F, -2.6F, -1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4103F, KeyframeAnimations.degreeVec(0.0F, -1.93F, -2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5862F, KeyframeAnimations.degreeVec(0.0F, -1.03F, -3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6448F, KeyframeAnimations.degreeVec(0.0F, -0.52F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7034F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.762F, KeyframeAnimations.degreeVec(0.0F, 0.52F, -4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8206F, KeyframeAnimations.degreeVec(0.0F, 1.03F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9379F, KeyframeAnimations.degreeVec(0.0F, 1.5F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0551F, KeyframeAnimations.degreeVec(0.0F, 2.3F, -3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1723F, KeyframeAnimations.degreeVec(0.0F, 2.82F, -2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3482F, KeyframeAnimations.degreeVec(0.0F, 3.0F, -0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.4654F, KeyframeAnimations.degreeVec(0.0F, 2.82F, 0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.6413F, KeyframeAnimations.degreeVec(0.0F, 2.3F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.7585F, KeyframeAnimations.degreeVec(0.0F, 1.5F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.8757F, KeyframeAnimations.degreeVec(0.0F, 0.52F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.993F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.0516F, KeyframeAnimations.degreeVec(0.0F, -0.52F, 4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1102F, KeyframeAnimations.degreeVec(0.0F, -1.03F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1688F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.3447F, KeyframeAnimations.degreeVec(0.0F, -2.3F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4619F, KeyframeAnimations.degreeVec(0.0F, -2.82F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.5205F, KeyframeAnimations.degreeVec(0.0F, -2.95F, 1.37F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone6", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -2.95F, 1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1172F, KeyframeAnimations.degreeVec(0.0F, -2.95F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2931F, KeyframeAnimations.degreeVec(0.0F, -2.6F, -1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4103F, KeyframeAnimations.degreeVec(0.0F, -1.93F, -2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5862F, KeyframeAnimations.degreeVec(0.0F, -1.03F, -3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.6448F, KeyframeAnimations.degreeVec(0.0F, -0.52F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7034F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.762F, KeyframeAnimations.degreeVec(0.0F, 0.52F, -4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8206F, KeyframeAnimations.degreeVec(0.0F, 1.03F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9379F, KeyframeAnimations.degreeVec(0.0F, 1.5F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0551F, KeyframeAnimations.degreeVec(0.0F, 2.3F, -3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1723F, KeyframeAnimations.degreeVec(0.0F, 2.82F, -2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3482F, KeyframeAnimations.degreeVec(0.0F, 3.0F, -0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.4654F, KeyframeAnimations.degreeVec(0.0F, 2.82F, 0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.6413F, KeyframeAnimations.degreeVec(0.0F, 2.3F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.7585F, KeyframeAnimations.degreeVec(0.0F, 1.5F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.8757F, KeyframeAnimations.degreeVec(0.0F, 0.52F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.993F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.0516F, KeyframeAnimations.degreeVec(0.0F, -0.52F, 4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1102F, KeyframeAnimations.degreeVec(0.0F, -1.03F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1688F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.3447F, KeyframeAnimations.degreeVec(0.0F, -2.3F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4619F, KeyframeAnimations.degreeVec(0.0F, -2.82F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.5205F, KeyframeAnimations.degreeVec(0.0F, -2.95F, 1.37F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone7", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1172F, KeyframeAnimations.degreeVec(0.0F, -2.3F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2931F, KeyframeAnimations.degreeVec(0.0F, -2.82F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4103F, KeyframeAnimations.degreeVec(0.0F, -3.0F, 0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5862F, KeyframeAnimations.degreeVec(0.0F, -2.82F, -0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7034F, KeyframeAnimations.degreeVec(0.0F, -2.3F, -2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8206F, KeyframeAnimations.degreeVec(0.0F, -1.5F, -3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9965F, KeyframeAnimations.degreeVec(0.0F, -0.52F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0551F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1137F, KeyframeAnimations.degreeVec(0.0F, 0.52F, -4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1723F, KeyframeAnimations.degreeVec(0.0F, 1.03F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2896F, KeyframeAnimations.degreeVec(0.0F, 1.5F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3482F, KeyframeAnimations.degreeVec(0.0F, 1.93F, -3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.4654F, KeyframeAnimations.degreeVec(0.0F, 2.6F, -2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.6413F, KeyframeAnimations.degreeVec(0.0F, 2.95F, -1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.7585F, KeyframeAnimations.degreeVec(0.0F, 2.95F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.8757F, KeyframeAnimations.degreeVec(0.0F, 2.6F, 1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.0516F, KeyframeAnimations.degreeVec(0.0F, 1.93F, 2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1688F, KeyframeAnimations.degreeVec(0.0F, 1.03F, 3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.2274F, KeyframeAnimations.degreeVec(0.0F, 0.52F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.3447F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4033F, KeyframeAnimations.degreeVec(0.0F, -0.52F, 4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4619F, KeyframeAnimations.degreeVec(0.0F, -1.03F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.5205F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 3.76F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bone8", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.1172F, KeyframeAnimations.degreeVec(0.0F, -2.3F, 3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2931F, KeyframeAnimations.degreeVec(0.0F, -2.82F, 2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4103F, KeyframeAnimations.degreeVec(0.0F, -3.0F, 0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5862F, KeyframeAnimations.degreeVec(0.0F, -2.82F, -0.69F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.7034F, KeyframeAnimations.degreeVec(0.0F, -2.3F, -2.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8206F, KeyframeAnimations.degreeVec(0.0F, -1.5F, -3.06F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9965F, KeyframeAnimations.degreeVec(0.0F, -0.52F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0551F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1137F, KeyframeAnimations.degreeVec(0.0F, 0.52F, -4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1723F, KeyframeAnimations.degreeVec(0.0F, 1.03F, -3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.2896F, KeyframeAnimations.degreeVec(0.0F, 1.5F, -3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3482F, KeyframeAnimations.degreeVec(0.0F, 1.93F, -3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.4654F, KeyframeAnimations.degreeVec(0.0F, 2.6F, -2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.6413F, KeyframeAnimations.degreeVec(0.0F, 2.95F, -1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.7585F, KeyframeAnimations.degreeVec(0.0F, 2.95F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.8757F, KeyframeAnimations.degreeVec(0.0F, 2.6F, 1.37F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.0516F, KeyframeAnimations.degreeVec(0.0F, 1.93F, 2.57F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.1688F, KeyframeAnimations.degreeVec(0.0F, 1.03F, 3.46F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.2274F, KeyframeAnimations.degreeVec(0.0F, 0.52F, 3.76F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.3447F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4033F, KeyframeAnimations.degreeVec(0.0F, -0.52F, 4.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.4619F, KeyframeAnimations.degreeVec(0.0F, -1.03F, 3.94F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.5205F, KeyframeAnimations.degreeVec(0.0F, -1.5F, 3.76F), AnimationChannel.Interpolations.LINEAR)
			))
			.build();
}
